# ---- Prod ----
FROM balenalib/raspberry-pi:20210225
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-11-jre:armhf \
 && rm -rf /var/lib/apt/lists/*
RUN mkdir /opt/app
WORKDIR /opt/app
COPY src/de.rnd7.huemqtt/target/huemqtt.jar .
COPY src/logback.xml .

CMD java -jar ./huemqtt.jar /var/lib/huemqtt/config.json
