# syntax=docker/dockerfile:1.17

FROM alpine:3.21

WORKDIR /

COPY hue2mqtt /hue2mqtt

RUN addgroup -S app && adduser -S app -G app
USER app:app

ENTRYPOINT ["/hue2mqtt", "/var/lib/huemqtt/config.json"]
