name: Application

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install
        run: |
          npm install

      - name: Lint/Test
        run: |
          npm run lint
          npm test

      - name: Build
        run: |
          npm run build
